# Generated by Django 5.2.8 on 2025-11-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(help_text="Введите место", max_length=250, verbose_name="Место")),
                ("time", models.TimeField(default="09:00", help_text="Укажите время", verbose_name="Время")),
                ("action", models.CharField(help_text="Введите действие", max_length=250, verbose_name="Действие")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        help_text="Является ли привычка приятной", verbose_name="Признак приятной привычки"
                    ),
                ),
                ("period", models.PositiveIntegerField(default=7, verbose_name="Периодичность")),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Введите вознаграждение",
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=60, help_text="Укажите время в секундах", verbose_name="Время на выполнение в секундах"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Укажите признак публичности", verbose_name="Признак публичности"
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите действие",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action"],
            },
        ),
    ]
